name: Lint

on:
  - push
  - pull_request

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install packages
        run: yarn install
      - name: ESLint
        run: yarn run lint